### PR TITLE
Add trufflehog workflow to secret scan

### LINKED ISSUE #296: Truffle Hog

### PR DESCRIPTION
**Pull request by samiwelthomasHO**
Fixes #296

### CODE REVIEW

**Review by michaelpearsonHO — COMMENTED** [review]
Couple of comments guys: -
- Should we pin to a version (instead of main).
- Does this replace all GitLeaks functionality and if so are we killing that off as part of another PR?
- This would ace as a pre-commit but you've probably already started on that.

**Comment by samiwelthomasHO** [comment]
> Couple of comments guys: -
> 
> * Should we pin to a version (instead of main).
> * Does this replace all GitLeaks functionality and if so are we killing that off as part of another PR?
> * This would ace as a pre-commit but you've probably already started on that.

I think pinning to main/latest here makes sense because we're always going to benefit from the latest updates from upstream trufflehog repo whereas if we pin to a version we risk falling behind or introduce a need to keep updating over time.

We could remove Gitleaks from the workflow. In practice I've seen trufflehog and git leaks pick up on different things so it may be worth keeping both for now?

As mentioned, pre-commit hook won't work because trufflehog scans the git commit history for leaks rather than the staged files of a commit, so we've introduced a pre-push hook to scan all commits before they are pushed up to Github. The pipeline check should remain in case someone tries to bypass the pre-push hook.

**Comment by michaelpearsonHO** [comment]
> I think pinning to main/latest here makes sense because we're always going to benefit from the latest updates from upstream trufflehog repo whereas if we pin to a version we risk falling behind or introduce a need to keep updating over time.

I would counter that slightly @samiwelthomasHO in that we have chosen to pin the versions of all dependencies to avoid any breaking changes to builds. Dependabot picks up any new releases to published GitHub Actions.

**Review by georgeowusuHO — APPROVED** [review]

**Review by michaelpearsonHO — APPROVED** [review]
Great stuff.

**Pull request merged**
