### PR TITLE
315 dashboard titles

### LINKED ISSUE #315: Dashboard titles
Update dashboard titles to align with k8s mixin naming conventions.

### PR DESCRIPTION
**Pull request by michaelpearsonHO**
resolves #315

### CODE REVIEW

**Review by georgeowusuHO — APPROVED** [review]
dashboards are now copied matching mixing folder

**Review by arifulhaqueHO — CHANGES_REQUESTED** [review]
Overview links need to be fixed
Change the service title to something more suitable.

**Comment by michaelpearsonHO** [comment]
> Overview links need to be fixed Change the service title to something more suitable.

URIs updated to include `sre-mac` prefix and now link correctly. 

`service` dashboard references to be updated as part of issue (https://github.com/HO-CTO/sre-monitoring-as-code/issues/322)

**Review by samiwelthomasHO — APPROVED** [review]
LGTM

**Comment by arifulhaqueHO** [comment]
I am happy with the links being changed. Please re request review when you have done your further changes.

**Comment by michaelpearsonHO** [comment]
> I am happy with the links being changed. Please re request review when you have done your further changes.

Further corrections flagged up by @georgeowusuHO to product view URIs (which I missed). Plus now rebased.

**Review by arifulhaqueHO — APPROVED** [review]
Looks good

**Pull request merged**
